### ISSUE TITLE
Almost none of the commands work

### ISSUE THREAD

**Issue by screendriver** [zpiman/wake-cli#6]
I installed `wake-cli` with `yarn global add wake-cli` and get following errors:

```sh
❯ wake -h
/Users/me/.config/yarn/global/node_modules/wol/index.js:16
    throw new Error("malformed MAC address '" + mac + "'");
    ^

Error: malformed MAC address '-h'
    at exports.createMagicPacket (/Users/me/.config/yarn/global/node_modules/wol/index.js:16:11)
    at Object.wake (/Users/me/.config/yarn/global/node_modules/wol/index.js:48:21)
    at Object.<anonymous> (/Users/me/.config/yarn/global/node_modules/wol/bin/wake:15:5)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
```

`wake list`, `wake add` and so on doesn't work as well. Yarn version `0.27.5`. Node version `8.1.3`

**Comment by mandulaj** [comment]
I sort of abandoned the project. I am going to look into it in my free time. But you are more than welcome to conduct your own investigation.

**Comment by mandulaj** [comment]
Actually, now that I think back, I have made a few recent changes that might have broken the parser. I will let you know as soon as I fix it.
